---
title: "STAT/MATH 495: Problem Set 02"
author: "WRITE YOUR NAMES HERE"
date: "2017-09-19"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    collapsed: false
    smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=8, fig.height=4.5)

# Load packages
library(tidyverse)

# Note the relative file path, and not absolute file path:
# http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/
train <- read_csv("data/train.csv")
```


# Exploratory Data Analysis

```{r}
ggplot(train, aes(x=full_sq, y=price_doc)) +
  geom_jitter()   # price is correlated with square footage

ggplot(train_small, aes(x=state, y=price_doc)) +
  geom_boxplot()   # state 4 has more expensive houses, NA has cheapest houses (in general)
train %>%
  group_by(state) %>%
  summarize(avg_price = mean(price_doc))

ggplot(train, aes(x=timestamp, y=price_doc)) +
  geom_point(alpha=0.3)
train %>%
  group_by(year(timestamp)) %>%
  summarize(price = mean(price_doc))   # average price goes up over time
```


# Model Fit

```{r}

```


# Create Submission File

```{r}

```

